#!/bin/bash

set -e

REPO_URL=$(git config --get remote.origin.url)
TEMP_DIR=$(mktemp -d)
BRANCH=gh-pages
TARGET_DIR=storybook

echo "Cloning $BRANCH branch from $REPO_URL into $TEMP_DIR"
git clone --branch $BRANCH $REPO_URL $TEMP_DIR

echo "Copying Storybook static files into $TEMP_DIR/$TARGET_DIR"
mkdir -p "$TEMP_DIR/$TARGET_DIR"
rm -rf "$TEMP_DIR/$TARGET_DIR"/*
cp -R storybook-static/* "$TEMP_DIR/$TARGET_DIR/"

# Add .nojekyll file to enable directory indexing on GitHub Pages
echo "Adding .nojekyll file for GitHub Pages"
cp .nojekyll "$TEMP_DIR/"

cd $TEMP_DIR

echo "Adding files to git"
git add $TARGET_DIR .nojekyll

if git diff --cached --quiet; then
  echo "No changes to commit"
else
  git commit -m "Update Storybook deployment in /$TARGET_DIR"
  echo "Pushing to $BRANCH branch"
  git push origin $BRANCH
fi

echo "Cleaning up"
rm -rf $TEMP_DIR

echo "Storybook deployed successfully to /$TARGET_DIR on $BRANCH branch"
