name: Deploy Storybook to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# peaceiris/actions-gh-pages needs contents: write to push to the gh-pages branch
permissions:
  contents: write

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20' # Use Node.js version >= 20 as specified in .clinerules
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook # Build Storybook static files (output to ./storybook-static)

      - name: Deploy Storybook to gh-pages/storybook directory
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Branch to deploy to
          publish_dir: ./storybook-static # Directory to deploy from the build
          destination_dir: ./storybook # Subdirectory to deploy into on the target branch
          # Optional: keep_files: false # Set to true to keep existing files in destination_dir
          # Optional: force_orphan: true # Set to true to create orphan commits
